### ISSUE TITLE
Plugin sends error flood when using very custom build command

### ISSUE THREAD

**Issue by rayriffy** [netlify/netlify-plugin-nextjs#533]
**Describe the bug**

I am building Next application with Nx monorepo to Netlify with heavily customized command. `next-plugin-netlify` cannot recognize those and send false-positive double error flood to deploy log on `onPreBuild`, `onBuild`, and `onPostBuild` lifecycle. But NextJS still being detected and deploy correctly

![CleanShot 2021-07-16 at 00 41 38](https://user-images.githubusercontent.com/22584594/125816766-4aa35eb0-396a-4407-9da9-83f1b68887a9.png)
![CleanShot 2021-07-16 at 00 42 12](https://user-images.githubusercontent.com/22584594/125816837-2fb82c00-0b75-4818-b7b7-79750d29363f.png)
![CleanShot 2021-07-16 at 00 42 26](https://user-images.githubusercontent.com/22584594/125816859-b349b3eb-8cec-40af-8b40-e87b06b93813.png)

**Expected behavior**

Error flood should not be visible

**Versions**
- Next.js: 11.0.1

**If you're using file-based installation**
- netlify.toml:

**Comment by norbertschuler** [comment]
We are getting the same error having this command within our `netlify.toml` file - we also have the same command in our deploy settings.
```
[build]
  command = "npm run build && npm run export"
  publish = "out"
```

Context of the build.
```
7:01:11 PM: ❯ Version
7:01:11 PM:   @netlify/build 15.11.5
7:01:11 PM: ​
7:01:11 PM: ❯ Flags
7:01:11 PM:   deployId: 60f069861f89db2565832087
7:01:11 PM: ​
7:01:11 PM: ❯ Current directory
7:01:11 PM:   /opt/build/repo
7:01:11 PM: ​
7:01:11 PM: ❯ Config file
7:01:11 PM:   /opt/build/repo/netlify.toml
7:01:11 PM: ​
7:01:11 PM: ❯ Context
7:01:11 PM:   production
7:01:11 PM: ​
7:01:11 PM: ❯ Installing plugins
7:01:11 PM:    - @netlify/plugin-nextjs@3.7.0
7:01:11 PM:    - netlify-plugin-next-dynamic@1.0.9
7:01:11 PM:    - netlify-plugin-cache-nextjs@1.4.0
7:01:39 PM: ​
7:01:39 PM: ❯ Loading plugins
7:01:39 PM:    - @netlify/plugin-nextjs@3.7.0 from Netlify app
7:01:39 PM:    - netlify-plugin-next-dynamic@1.0.9 from netlify.toml
7:01:39 PM:    - netlify-plugin-cache-nextjs@1.4.0 from netlify.toml
```

We currently have a problem not building anymore without changing our sources with the following error:
```
7:01:42 PM: 
7:01:42 PM:   3. build.command from netlify.toml                            
7:01:42 PM: 
7:01:42 PM: ​
7:01:42 PM: $ npm run build && npm run export
7:01:42 PM: > planet-web2@0.2.0 build /opt/build/repo
7:01:42 PM: > next build
...
7:04:41 PM: Failed to compile.
7:04:41 PM: 
7:04:41 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'asciify-image' in '/opt/build/repo/node_modules/probe.gl/dist/es5/lib'
7:04:41 PM: > Build error occurred
7:04:41 PM: Error: > Build failed because of webpack errors
7:04:41 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:17:924
7:04:41 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)
7:04:41 PM: npm ERR! code ELIFECYCLE
7:04:41 PM: npm ERR! errno 1
7:04:41 PM: npm ERR! planet-web2@0.2.0 build: `next build`
7:04:41 PM: npm ERR! Exit status 1
7:04:41 PM: npm ERR!
7:04:41 PM: npm ERR! Failed at the planet-web2@0.2.0 build script.
7:04:41 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
7:04:41 PM: npm ERR! A complete log of this run can be found in:
7:04:41 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-07-15T17_04_41_542Z-debug.log

```

**Comment by lindsaylevine** [comment]
@rayriffy hey ray! thanks for reporting :). i haven't had the opportunity to work much on next recently so i defer to @ascorbic who's done all the awesome monorepo support work and has been juggling a ton of other major next.js initiatives. he should be able to offer insight into these floods and maybe patch it up for you.

@norbertschuler hey norbert! it seems like that second error you shared _might_ actually be different from the parseNpmScript errors but still related to the script work since it does seem like a random, pure `next build` error (and not a plugin-specific error). i'll defer to matt (@ascorbic) again but perhaps a separate issue may be necessary!

**Comment by ascorbic** [comment]
Hey. Thanks for the report. This looks like the same issue as #528, and should be fixed in version 3.7.1 of the plugin. It will be auto-installed later today, but if you want to use it now, install `@netlify/plugin-nextjs@latest`. Closing as duplicate of #528, but please do comment to say whether 3.7.1 fixes it for you

**Comment by norbertschuler** [comment]
Netlify now is using @netlify/plugin-nextjs@3.7.1 and our builds are working again :-)

**Comment by ascorbic** [comment]
Great! Thanks for the update.

**Comment by rayriffy** [comment]
@ascorbic i still have an error throw from `@netlify/plugin-nextjs@3.7.1`, but now in more detail.

![CleanShot 2021-07-20 at 00 45 12](https://user-images.githubusercontent.com/22584594/126188417-aa762c66-80d5-433c-8367-14b34a621695.png)

![CleanShot 2021-07-20 at 00 46 57](https://user-images.githubusercontent.com/22584594/126188547-1aac1377-e824-4e21-84dd-ab998ed8b5cd.png)
