### ISSUE TITLE
[Bug]: 404 on JS and CSS files

### ISSUE THREAD

**Issue by kamerat** [netlify/netlify-plugin-nextjs#990]
### Steps to reproduce

1. go to https://61b8ba533ac12329b6de8d74--nyladeklar.netlify.app/
2. Page looks broken due to no css/js
3. Inspect network tab to see 404's

![image](https://user-images.githubusercontent.com/11461961/146029570-03e4b4c3-ccfb-4dc0-ba7f-bec8a18059df.png)

### Plugin version

4.0.0

### More information about your build

- [ ] I am building using the CLI
- [X] I am building using file-based configuration (`netlify.toml`)

### Your `netlify.toml` file

<details>
  <summary><strike>netlify.toml</strike> Netlify build settings</summary>
  No .toml file for this project, everything is default except this:
  
![image](https://user-images.githubusercontent.com/11461961/146030389-400cbaaa-ee02-459a-baf3-4d121890052f.png)

</details>

### Relevant log output (or link to your logs)

<details>
  <summary>Build logs</summary>
  
  https://app.netlify.com/sites/nyladeklar/deploys/61b8ba533ac12329b6de8d74
  
```
4:37:55 PM: Build ready to start
4:37:57 PM: build-image version: a6bb34428a07e7de82f4df5dfe1843fbde91f670 (focal)
4:37:57 PM: build-image tag: v4.5.1
4:37:57 PM: buildbot version: 5284b4d1b8b4cf691b29019968d8e4eb3089acdd
4:37:57 PM: Fetching cached dependencies
4:37:57 PM: Starting to download cache of 407.4MB
4:37:59 PM: Finished downloading cache in 1.968286478s
4:37:59 PM: Starting to extract cache
4:38:18 PM: Finished extracting cache in 18.981575001s
4:38:18 PM: Finished fetching cache in 21.105437945s
4:38:18 PM: Starting to prepare the repo for build
4:38:19 PM: Preparing Git Reference pull/152/head
4:38:19 PM: Parsing package.json dependencies
4:38:20 PM: Starting build script
4:38:20 PM: Installing dependencies
4:38:20 PM: Python version set to 2.7
4:38:21 PM: Started restoring cached node version
4:38:23 PM: Finished restoring cached node version
4:38:24 PM: v16.13.1 is already installed.
4:38:24 PM: Now using node v16.13.1 (npm v8.1.2)
4:38:24 PM: Started restoring cached build plugins
4:38:24 PM: Finished restoring cached build plugins
4:38:24 PM: Attempting ruby version 2.7.2, read from environment
4:38:26 PM: Using ruby version 2.7.2
4:38:27 PM: Using PHP version 8.0
4:38:27 PM: Started restoring cached node modules
4:38:27 PM: Finished restoring cached node modules
4:38:27 PM: Started restoring cached go cache
4:38:27 PM: Finished restoring cached go cache
4:38:27 PM: go version go1.16.5 linux/amd64
4:38:27 PM: go version go1.16.5 linux/amd64
4:38:27 PM: Installing missing commands
4:38:27 PM: Verify run directory
4:38:29 PM: ​
4:38:29 PM: ────────────────────────────────────────────────────────────────
4:38:29 PM:   Netlify Build                                                 
4:38:29 PM: ────────────────────────────────────────────────────────────────
4:38:29 PM: ​
4:38:29 PM: ❯ Version
4:38:29 PM:   @netlify/build 20.3.1
4:38:29 PM: ​
4:38:29 PM: ❯ Flags
4:38:29 PM:   baseRelDir: true
4:38:29 PM:   buildId: 61b8ba533ac12329b6de8d72
4:38:29 PM:   deployId: 61b8ba533ac12329b6de8d74
4:38:30 PM: ​
4:38:30 PM: ❯ Current directory
4:38:30 PM:   /opt/build/repo
4:38:30 PM: ​
4:38:30 PM: ❯ Config file
4:38:30 PM:   No config file was defined: using default values.
4:38:30 PM: ​
4:38:30 PM: ❯ Context
4:38:30 PM:   deploy-preview
4:38:30 PM: ​
4:38:30 PM: ❯ Loading plugins
4:38:30 PM:    - @netlify/plugin-nextjs@4.0.0 from Netlify app
4:38:30 PM: ​
4:38:30 PM: ────────────────────────────────────────────────────────────────
4:38:30 PM:   1. @netlify/plugin-nextjs (onPreBuild event)                  
4:38:30 PM: ────────────────────────────────────────────────────────────────
4:38:30 PM: ​
4:38:31 PM: Next.js cache restored.
4:38:31 PM: Netlify configuration property "build.environment.NEXT_PRIVATE_TARGET" value changed.
4:38:31 PM: ​
4:38:31 PM: (@netlify/plugin-nextjs onPreBuild completed in 641ms)
4:38:31 PM: ​
4:38:31 PM: ────────────────────────────────────────────────────────────────
4:38:31 PM:   2. Build command from Netlify app                             
4:38:31 PM: ────────────────────────────────────────────────────────────────
4:38:31 PM: ​
4:38:31 PM: $ npm run build
4:38:32 PM: > eloway-io@0.1.0 build
4:38:32 PM: > next build
4:38:33 PM: info  - Checking validity of types...
4:39:04 PM: ./components/Footer/components/Socials.tsx
4:39:04 PM: 29:29  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/IconTitleText/IconTitleText.tsx
4:39:04 PM: 12:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/ImageWithCaption/ImageWithCaption.tsx
4:39:04 PM: 14:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/Input/decision_maker/DecisionMaker.tsx
4:39:04 PM: 14:9  Warning: Visible, non-interactive elements with click handlers must have at least one keyboard listener.  jsx-a11y/click-events-have-key-events
4:39:04 PM: ./components/Input/mailing_list/MailingList.tsx
4:39:04 PM: 14:9  Warning: Visible, non-interactive elements with click handlers must have at least one keyboard listener.  jsx-a11y/click-events-have-key-events
4:39:04 PM: ./components/MediaAndContent/MediaAndContent.tsx
4:39:04 PM: 71:29  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: 80:29  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/Section/Section.tsx
4:39:04 PM: 29:21  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/TextOnImage/TextOnImage.tsx
4:39:04 PM: 14:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: ./components/Tile/Tile.tsx
4:39:04 PM: 12:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See https://nextjs.org/docs/messages/no-img-element.  @next/next/no-img-element
4:39:04 PM: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
4:39:04 PM: info  - Creating an optimized production build...
4:39:17 PM: info  - Compiled successfully
4:39:17 PM: info  - Collecting page data...
4:39:23 PM: info  - Generating static pages (0/71)
4:39:23 PM: next-translate - compiled page: /[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/contact-us/contact-us-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/contact-us/contact-us-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies/charging-stations-companies-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/news/[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies/charging-stations-companies-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies/charging-stations-companies-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies/charging-stations-companies-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/charging-stations-companies - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/condominium/condominium-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/hotels/hotels-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/hotels/hotels-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/condominium/condominium-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/hotels - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/hotels - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:23 PM: info  - Generating static pages (17/71)
4:39:23 PM: next-translate - compiled page: /_hidden/evcharging/new-construction/new-construction-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/new-construction/new-construction-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/new-construction/new-construction-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/new-construction/new-construction-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy/privacy-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy/privacy-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy/privacy-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/privacy/privacy-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /datenschutzerklarung - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /datenschutzerklarung - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /kontaktiere-uns - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /ladelosungen-fur-hotels - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /kontaktiere-uns - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /ladelosungen-fur-hotels - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /ladelosungen-fur-neubauten - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /ladelosungen-fur-neubauten - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: info  - Generating static pages (35/71)
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/condominium/condominium-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/condominium/condominium-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/condominium - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/404/404-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging/condominium - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/404/404-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/contact-us/contact-us-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/sandbox - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/sandbox - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/contact-us/contact-us-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /[slug] - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /404 - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /404 - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/news - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: / - locale: de - namespaces: common, form, home - used loader: getStaticProps
4:39:24 PM: info  - Generating static pages (53/71)
4:39:24 PM: next-translate - compiled page: /_hidden/404/404-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/news - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/404/404-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/evcharging - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/about-us - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/about-us - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/index-no - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/index-no - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/index-de - locale: no - namespaces: common, form - used loader: getStaticProps
4:39:24 PM: next-translate - compiled page: /_hidden/index-de - locale: de - namespaces: common, form - used loader: getStaticProps
4:39:25 PM: next-translate - compiled page: / - locale: no - namespaces: common, form, home - used loader: getStaticProps
4:39:25 PM: info  - Generating static pages (71/71)
4:39:26 PM: info  - Finalizing page optimization...
4:39:26 PM: Page                                                                                Size     First Load JS
4:39:26 PM: ┌ ● /                                                                               1.01 kB         135 kB
4:39:26 PM: ├   /_app                                                                           0 B            77.5 kB
4:39:26 PM: ├ ● /_hidden/404/404-de                                                             2.79 kB        87.5 kB
4:39:26 PM: ├ ● /_hidden/404/404-no                                                             2.74 kB        87.4 kB
4:39:26 PM: ├ ● /_hidden/about-us                                                               1.76 kB         118 kB
4:39:26 PM: ├   └ css/0b5ab9bb2b69acc0.css                                                      2.56 kB
4:39:26 PM: ├ ● /_hidden/contact-us/contact-us-de                                               220 B          89.5 kB
4:39:26 PM: ├ ● /_hidden/contact-us/contact-us-no                                               4.69 kB        89.4 kB
4:39:26 PM: ├ ● /_hidden/evcharging                                                             3.03 kB         123 kB
4:39:26 PM: ├   └ css/65f1d5a15f0b94da.css                                                      2.96 kB
4:39:26 PM: ├ ● /_hidden/evcharging/charging-stations-companies                                 2.3 kB         97.1 kB
4:39:26 PM: ├ ● /_hidden/evcharging/charging-stations-companies/charging-stations-companies-de  6.1 kB         94.5 kB
4:39:26 PM: ├   └ css/86781e33ae6b4cfb.css                                                      3.16 kB
4:39:26 PM: ├ ● /_hidden/evcharging/charging-stations-companies/charging-stations-companies-no  241 B          95.1 kB
4:39:26 PM: ├ ● /_hidden/evcharging/condominium                                                 2.35 kB        95.1 kB
4:39:26 PM: ├   └ css/c5e5a45105ea1e7f.css                                                      2.94 kB
4:39:26 PM: ├ ● /_hidden/evcharging/condominium/condominium-de                                  231 B            93 kB
4:39:26 PM: ├   └ css/024c686c3c8f70e6.css                                                      2.87 kB
4:39:26 PM: ├ ● /_hidden/evcharging/condominium/condominium-no                                  4.32 kB        92.7 kB
4:39:26 PM: ├   └ css/b47c860a4ac0beb1.css                                                      2.88 kB
4:39:26 PM: ├ ● /_hidden/evcharging/hotels                                                      950 B          92.7 kB
4:39:26 PM: ├ ● /_hidden/evcharging/hotels/hotels-de                                            230 B            92 kB
4:39:26 PM: ├ ● /_hidden/evcharging/new-construction/new-construction-de                        235 B            92 kB
4:39:26 PM: ├ ● /_hidden/evcharging/new-construction/new-construction-no                        3.21 kB        87.9 kB
4:39:26 PM: ├   └ css/6ea638cdd28da784.css                                                      2.65 kB
4:39:26 PM: ├ ● /_hidden/index-de                                                               220 B           134 kB
4:39:26 PM: ├ ● /_hidden/index-no                                                               5.62 kB         135 kB
4:39:26 PM: ├   └ css/17e564d9e30c6bdd.css                                                      3.32 kB
4:39:26 PM: ├ ● /_hidden/news                                                                   2.27 kB         119 kB
4:39:26 PM: ├   └ css/cdd032d2881d0058.css                                                      3.06 kB
4:39:26 PM: ├ ● /_hidden/news/[slug] (407 ms)                                                   16.5 kB         133 kB
4:39:26 PM: ├   └ css/aea9c87fb7a8e41b.css                                                      2.6 kB
4:39:26 PM: ├   └ /no/_hidden/news/sample-heading-de (407 ms)
4:39:26 PM: ├ ● /_hidden/privacy                                                                971 B          94.1 kB
4:39:26 PM: ├ ● /_hidden/privacy/privacy-de                                                     221 B          93.3 kB
4:39:26 PM: ├ ● /_hidden/privacy/privacy-no                                                     2.73 kB        87.4 kB
4:39:26 PM: ├ ● /_hidden/sandbox                                                                5.59 kB        83.1 kB
4:39:26 PM: ├   └ css/77daffc02e9a0cd4.css                                                      1.73 kB
4:39:26 PM: ├ ● /[slug] (4282 ms)                                                               2.59 kB         136 kB
4:39:26 PM: ├   └ css/b99e51052d033956.css                                                      3.84 kB
4:39:26 PM: ├   ├ /no/something (1461 ms)
4:39:26 PM: ├   ├ /no/example (1081 ms)
4:39:26 PM: ├   ├ /no/page-four (891 ms)
4:39:26 PM: ├   ├ /no/slug-test (558 ms)
4:39:26 PM: ├   └ /no/another-page
4:39:26 PM: ├ ○ /404                                                                            3.01 kB        87.7 kB
4:39:26 PM: ├ ● /datenschutzerklarung                                                           930 B          94.1 kB
4:39:26 PM: ├ ● /kontaktiere-uns                                                                941 B          90.2 kB
4:39:26 PM: ├ ● /ladelosungen-fur-hotels                                                        951 B          92.7 kB
4:39:26 PM: └ ● /ladelosungen-fur-neubauten                                                     952 B          92.7 kB
4:39:26 PM: + First Load JS shared by all                                                       77.5 kB
4:39:26 PM:   ├ chunks/framework-d5d37a8f37f0392d.js                                            42 kB
4:39:26 PM:   ├ chunks/main-4874bcbb58314617.js                                                 29 kB
4:39:26 PM:   ├ chunks/pages/_app-404f944a55548927.js                                           4.28 kB
4:39:26 PM:   ├ chunks/webpack-f6f3c391358fe789.js                                              2.26 kB
4:39:26 PM:   └ css/f12ae81fa4dbd33c.css                                                        1.36 kB
4:39:26 PM: ○  (Static)  automatically rendered as static HTML (uses no initial props)
4:39:26 PM: ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
4:39:26 PM: > eloway-io@0.1.0 postbuild
4:39:26 PM: > next-sitemap --config next-sitemap.config.js
4:39:26 PM: ​
4:39:26 PM: (build.command completed in 54.7s)
4:39:26 PM: ​
4:39:26 PM: ────────────────────────────────────────────────────────────────
4:39:26 PM:   3. @netlify/plugin-nextjs (onBuild event)                     
4:39:26 PM: ────────────────────────────────────────────────────────────────
4:39:26 PM: ​
4:39:26 PM: Moving static page files to serve from CDN...
4:39:26 PM: Moved 124 files
4:39:26 PM: Netlify configuration property "redirects" value changed to [
4:39:26 PM:   {
4:39:26 PM:     from: '/_next/image*',
4:39:26 PM:     query: { url: ':url', w: ':width', q: ':quality' },
4:39:26 PM:     to: '/_ipx/w_:width,q_:quality/:url',
4:39:26 PM:     status: 301
4:39:26 PM:   },
4:39:26 PM:   { from: '/_ipx/*', to: '/.netlify/builders/_ipx', status: 200 },
4:39:26 PM:   { from: '/cache/*', to: '/404.html', status: 404, force: true },
4:39:26 PM:   { from: '/server/*', to: '/404.html', status: 404, force: true },
4:39:26 PM:   { from: '/serverless/*', to: '/404.html', status: 404, force: true },
4:39:26 PM:   { from: '/traces', to: '/404.html', status: 404, force: true },
4:39:26 PM:   {
4:39:26 PM:     from: '/routes-manifest.json',
4:39:26 PM:     to: '/404.html',
4:39:26 PM:     status: 404,
4:39:26 PM:     force: true
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/build-manifest.json',
4:39:26 PM:     to: '/404.html',
4:39:26 PM:     status: 404,
4:39:26 PM:     force: true
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/prerender-manifest.json',
4:39:26 PM:     to: '/404.html',
4:39:26 PM:     status: 404,
4:39:26 PM:     force: true
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/react-loadable-manifest.json',
4:39:26 PM:     to: '/404.html',
4:39:26 PM:     status: 404,
4:39:26 PM:     force: true
4:39:26 PM:   },
4:39:26 PM:   { from: '/BUILD_ID', to: '/404.html', status: 404, force: true },
4:39:26 PM:   {
4:39:26 PM:     from: '/:locale/_next/static/*',
4:39:26 PM:     to: '/static/:splat',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   { from: '/_next/static/*', to: '/static/:splat', status: 200 },
4:39:26 PM:   {
4:39:26 PM:     from: '/api',
4:39:26 PM:     to: '/.netlify/functions/___netlify-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/api/*',
4:39:26 PM:     to: '/.netlify/functions/___netlify-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/_redirects',
4:39:26 PM:     to: '/_redirects',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/android-chrome-192x192.png',
4:39:26 PM:     to: '/android-chrome-192x192.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/android-chrome-512x512.png',
4:39:26 PM:     to: '/android-chrome-512x512.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/apple-touch-icon.png',
4:39:26 PM:     to: '/apple-touch-icon.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/browserconfig.xml',
4:39:26 PM:     to: '/browserconfig.xml',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/favicon-16x16.png',
4:39:26 PM:     to: '/favicon-16x16.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/favicon-32x32.png',
4:39:26 PM:     to: '/favicon-32x32.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/favicon.ico',
4:39:26 PM:     to: '/favicon.ico',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/mstile-150x150.png',
4:39:26 PM:     to: '/mstile-150x150.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/safari-pinned-tab.svg',
4:39:26 PM:     to: '/safari-pinned-tab.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/site.webmanifest',
4:39:26 PM:     to: '/site.webmanifest',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/sitemap.xml',
4:39:26 PM:     to: '/sitemap.xml',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Air.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Air.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-AirItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-AirItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Black.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Black.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-BlackItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-BlackItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Bold.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Bold.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-BoldItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-BoldItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Light.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Light.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-LightItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-LightItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Medium.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Medium.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-MediumItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-MediumItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Regular.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Regular.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-RegularItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-RegularItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-Thin.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-Thin.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/fonts/AeonikPro-ThinItalic.woff2',
4:39:26 PM:     to: '/fonts/AeonikPro-ThinItalic.woff2',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/Construction.jpeg',
4:39:26 PM:     to: '/img/Construction.jpeg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/Ladeboks-Hvit.svg',
4:39:26 PM:     to: '/img/Ladeboks-Hvit.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/Ladeklar_Negativ.svg',
4:39:26 PM:     to: '/img/Ladeklar_Negativ.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/Ladeklar_Positiv.svg',
4:39:26 PM:     to: '/img/Ladeklar_Positiv.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/angarde.png',
4:39:26 PM:     to: '/img/angarde.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/bente.png',
4:39:26 PM:     to: '/img/bente.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/charger.jpg',
4:39:26 PM:     to: '/img/charger.jpg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/chargingCar.png',
4:39:26 PM:     to: '/img/chargingCar.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/chargingappzap.png',
4:39:26 PM:     to: '/img/chargingappzap.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/cooperative.png',
4:39:26 PM:     to: '/img/cooperative.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/easeeChargerOutside.png',
4:39:26 PM:     to: '/img/easeeChargerOutside.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/futurecar.png',
4:39:26 PM:     to: '/img/futurecar.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/hotel.jpeg',
4:39:26 PM:     to: '/img/hotel.jpeg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/ladeklarCharging2.png',
4:39:26 PM:     to: '/img/ladeklarCharging2.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/ladeklarplay.png',
4:39:26 PM:     to: '/img/ladeklarplay.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/metaIndex.png',
4:39:26 PM:     to: '/img/metaIndex.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/om-oss-background.jpg',
4:39:26 PM:     to: '/img/om-oss-background.jpg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/penger-hvit.svg',
4:39:26 PM:     to: '/img/penger-hvit.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/roads.png',
4:39:26 PM:     to: '/img/roads.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/support-grønn.svg',
4:39:26 PM:     to: '/img/support-grønn.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/technicalsite.png',
4:39:26 PM:     to: '/img/technicalsite.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/waterfall.png',
4:39:26 PM:     to: '/img/waterfall.png',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/socials/Facebook.svg',
4:39:26 PM:     to: '/img/socials/Facebook.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/socials/Instagram.svg',
4:39:26 PM:     to: '/img/socials/Instagram.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/img/socials/Linkedin.svg',
4:39:26 PM:     to: '/img/socials/Linkedin.svg',
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/*',
4:39:26 PM:     to: '/.netlify/functions/___netlify-handler',
4:39:26 PM:     status: 200,
4:39:26 PM:     conditions: { Cookie: [Array] },
4:39:26 PM:     force: true
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/_next/data/Mbk-Iq__KTiAEuAS9FjrK/:slug.json',
4:39:26 PM:     to: '/.netlify/builders/___netlify-odb-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/_next/data/Mbk-Iq__KTiAEuAS9FjrK/_hidden/news/:slug.json',
4:39:26 PM:     to: '/.netlify/builders/___netlify-odb-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/:slug',
4:39:26 PM:     to: '/.netlify/builders/___netlify-odb-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/_hidden/news/:slug',
4:39:26 PM:     to: '/.netlify/builders/___netlify-odb-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   },
4:39:26 PM:   {
4:39:26 PM:     from: '/*',
4:39:26 PM:     to: '/.netlify/functions/___netlify-handler',
4:39:26 PM:     status: 200
4:39:26 PM:   }
4:39:26 PM: ].
4:39:26 PM: ​
4:39:26 PM: (@netlify/plugin-nextjs onBuild completed in 327ms)
4:39:26 PM: ​
4:39:26 PM: ────────────────────────────────────────────────────────────────
4:39:26 PM:   4. Functions bundling                                         
4:39:26 PM: ────────────────────────────────────────────────────────────────
4:39:26 PM: ​
4:39:26 PM: Packaging Functions from .netlify/functions-internal directory:
4:39:26 PM:  - ___netlify-handler/___netlify-handler.js
4:39:26 PM:  - ___netlify-odb-handler/___netlify-odb-handler.js
4:39:26 PM:  - _ipx/_ipx.js
4:39:26 PM: ​
4:39:26 PM: Packaging Functions from .netlify/functions directory:
4:39:26 PM:  - get_asana.js
4:39:26 PM:  - get_cooperatives.js
4:39:26 PM:  - get_pipedrive.js
4:39:26 PM:  - get_site.js
4:39:26 PM:  - post_feedbackform.js
4:39:26 PM:  - submission-created-custom.js
4:39:26 PM: ​
4:40:19 PM: ​
4:40:19 PM: (Functions bundling completed in 52.6s)
4:40:19 PM: ​
4:40:19 PM: ────────────────────────────────────────────────────────────────
4:40:19 PM:   5. @netlify/plugin-nextjs (onPostBuild event)                 
4:40:19 PM: ────────────────────────────────────────────────────────────────
4:40:19 PM: ​
4:40:20 PM: Next.js cache saved.
4:40:20 PM: ​
4:40:20 PM: (@netlify/plugin-nextjs onPostBuild completed in 1.3s)
4:40:20 PM: ​
4:40:20 PM: ────────────────────────────────────────────────────────────────
4:40:20 PM:   6. Deploy site                                                
4:40:20 PM: ────────────────────────────────────────────────────────────────
4:40:20 PM: ​
4:40:20 PM: Starting to deploy site from '.next'
4:40:21 PM: Creating deploy tree 
4:40:21 PM: Creating deploy upload records
4:40:21 PM: 120 new files to upload
4:40:21 PM: 2 new functions to upload
4:40:31 PM: Site deploy was successfully initiated
4:40:31 PM: ​
4:40:31 PM: (Deploy site completed in 11.2s)
4:40:32 PM: ​
4:40:32 PM: ────────────────────────────────────────────────────────────────
4:40:32 PM:   Netlify Build Complete                                        
4:40:32 PM: ────────────────────────────────────────────────────────────────
4:40:32 PM: ​
4:40:32 PM: (Netlify Build completed in 2m 2.1s)
4:40:32 PM: Starting post processing
4:40:32 PM: Caching artifacts
4:40:32 PM: Started saving node modules
4:40:32 PM: Finished saving node modules
4:40:32 PM: Started saving build plugins
4:40:32 PM: Finished saving build plugins
4:40:32 PM: Started saving pip cache
4:40:32 PM: Finished saving pip cache
4:40:32 PM: Started saving emacs cask dependencies
4:40:32 PM: Finished saving emacs cask dependencies
4:40:32 PM: Started saving maven dependencies
4:40:32 PM: Post processing - HTML
4:40:32 PM: Finished saving maven dependencies
4:40:32 PM: Started saving boot dependencies
4:40:32 PM: Finished saving boot dependencies
4:40:32 PM: Started saving rust rustup cache
4:40:32 PM: Finished saving rust rustup cache
4:40:32 PM: Started saving go dependencies
4:40:32 PM: Finished saving go dependencies
4:40:32 PM: Build script success
4:40:40 PM: Post processing - header rules
4:40:40 PM: Post processing - redirect rules
4:40:40 PM: Post processing done
4:40:41 PM: Site is live ✨
4:42:00 PM: Finished processing build request in 4m3.505140517s
```

</details>

**Comment by ascorbic** [comment]
Hi. If you go to the deploy page, there should be a tiny little arrow link to download the deploy:
![image](https://user-images.githubusercontent.com/213306/146046229-d60fe16a-29da-4814-ad41-670d40efed34.png)

 Could you do that and see if the missing files exist in the bundle? They would be in `static`

**Comment by kamerat** [comment]
>  If you go to the deploy page, there should be a tiny little arrow link to download the deploy:

Wow, I've never seen that button. Really neat! Thanks for the tip.

> Could you do that and see if the missing files exist in the bundle? They would be in `static`

I can confirm that they do exist in the bundle under /static. However I noticed in the network tab on the failing site, the path  is `https://deploy-preview-152--nyladeklar.netlify.app/_next/static/chunks/webpack-f6f3c391358fe789.js` not 
`https://deploy-preview-152--nyladeklar.netlify.app/static/chunks/webpack-f6f3c391358fe789.js`

I tested to go to https://deploy-preview-152--nyladeklar.netlify.app/static/chunks/webpack-f6f3c391358fe789.js and it works. 

Seems the _next part of the url is messing things about?

Is this something I have configured wrongly, or is this a bug?

Thank you for your quick reply.

**Comment by vpreponen** [comment]
I had the same issue and fixed it with a redirect.

```
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 301
  force = true
```

**Comment by ascorbic** [comment]
The strange thing is that if you look at the build logs you can see that there is already a rewrite that does that:

`{ from: '/_next/static/*', to: '/static/:splat', status: 200 }`

The file will be in the top level in `static`, rather than in `_next`, and the rewrite should handle it. Is the file in there?

**Comment by ascorbic** [comment]
Thanks. So it looks like the pages are there, but for some reason the auto-generated redirect isn't working. Looking at the logs it seems you have an existing `_redirects` file. Coudl you share it please?

**Comment by kamerat** [comment]
This is the current _redirects file:

<details>
<summary>
_redirects
</summary>

```
/elbillading-borettslag-sameie/ladeabonnement/ladeklar /ladeabonnement-elbil/boligportal/

/ladeabonnement/ladeklar /ladeabonnement-elbil/boligportal/

/ladeabonnement /ladeabonnement-elbil/

/ladeabonnement-elbil/ladeklar /ladeabonnement-elbil/boligportal/

/bestilling /ladeabonnement-elbil/boligportal/

/elbillading-borettslag-sameie/ladeabonnement/ladeklar* /ladeabonnement-elbil/boligportal/

/bestill-elbillader-ladeklar* /ladeabonnement-elbil/boligportal/

/elbillading-borettslag-sameie/installere-elbillader /installere-elbillader/

/befaring-elbillader-borettslag-sameie /installere-elbillader/

/elbillading-borettslag-sameie/ladeabonnement/ladeklar /ladeabonnement-elbil/boligportal/

/portal /ladeabonnement-elbil/boligportal/

/elbillader-borettslag-sameie-pris/ /elbillading/pris-elbillader/

/elbillading-borettslag-sameie/pris-elbillader /elbillading/pris-elbillader/

/elbillading-borettslag-sameie/webinar/ /webinar/

/elbillading-borettslag-sameie/ladeabonnement/ /ladeabonnement-elbil/

/elbil-borettslag-regler/ /elbillading/borettslag-sameie/elbil-borettslag-regler/

/elbillading/borettslag-sameie/regler /elbillading/borettslag-sameie/elbil-borettslag-regler/

/elbillading-borettslag-sameie/leie-av-ladeanlegg/ /elbillading/leie-av-ladeanlegg/

/elbillading-borettslag-sameie/kjop-av-ladeanlegg/ /elbillading/kjop-av-ladeanlegg/

/elbillading-borettslag-sameie/drift-av-ladeanlegg/ /elbillading/drift-av-ladeanlegg/

/elbillading/borettslag-sameie/leie-av-ladeanlegg /elbillading/leie-av-ladeanlegg/

/elbillading/borettslag-sameie/kjop-av-ladeanlegg /elbillading/kjop-av-ladeanlegg/

/elbillading/borettslag-sameie/drift-av-ladeanlegg /elbillading/drift-av-ladeanlegg/

/elbillading-borettslag-sameie/ /elbillading/borettslag-sameie/

/hjelp/ /support/hjelp/

/elbillading/bedrift/ /elbillading/ladestasjoner-bedrift/

/ofte-stilte-sporsmal/ /support/ofte-stilte-sporsmal/

/brukermanual-ladeboks/ /support/brukermanual-ladeboks/

/ledige-stillinger https://career.elaway.io/

/link/overforing /bestilling

/link/bestill /bestilling

/link/bestille-ladestasjon https://forms.office.com/Pages/ResponsePage.aspx?id=xxx&embed=true%22&dtmSource=%2Fladeplass%2Fbestill

/link/overfore-ladestasjon https://forms.office.com/Pages/ResponsePage.aspx?id=xxx&dtmSource=%2Fladeplass%2Foverforing

/partner-leads https://forms.office.com/Pages/ResponsePage.aspx?id=xxx

/partner/leads https://forms.office.com/Pages/ResponsePage.aspx?id=xxx

/elbillading/ladeklar-erfaringer /elaway-erfaringer/

/effekttariff /ladeanlegg/effekttariff

/lastbalansering-elbil /ladeanlegg/lastbalansering-elbil

/bestill /ladeabonnement-elbil/boligportal/

/* /404/ 404/

```

</details>

**Comment by kamerat** [comment]
I noticed now when providing you with the_redirects file, that the hidden gem `/* /404/ 404/` was lurking at the bottom there. 🤦‍♂️ I removed this in a test commit and now netlify builds correctly! 🎉 I have to talk to a team member on why this was added previously. However, odd that this does not break the page when using netlify-plugin-nextjs@3.9.1 🤔

**Comment by ascorbic** [comment]
Aha! That's great news. I spotted that and was just about to reply. I think I'll add the `_redirects` file to the issue template, but also add a build time check for root level redirects liek that.

**Comment by kamerat** [comment]
That's some good ideas! Thank you a lot for helping out here, and thanks for the good tips along the way. I really appreciate your time.

**Comment by ascorbic** [comment]
No worries. Thanks for the report and your help in tracking it down.

**Comment by eramdam** [comment]
Sorry to bump this thread, but I'm running into a similar issue, I have no conflicting redirects in `_redirects` and the workaround shared by @vpreponen doesn't seem to fix the issue either. 

Here are relevant the links:
- https://deploy-preview-15--bettertw.netlify.app/
- [_redirects](https://github.com/eramdam/better.tw/blob/next.js/public/_redirects)
- [netlify.toml](https://github.com/eramdam/better.tw/blob/next.js/netlify.toml)

I also attached the zip generated on the deploy page, and I can confirm that the JS/CSS assets return a 404 when running locally. However, when viewing in a browser, they seem to return a 200 just fine, but there's a CSP error popping in the console.


[deploy-61caf38bc8ffb800084bdfdf.zip](https://github.com/netlify/netlify-plugin-nextjs/files/7784430/deploy-61caf38bc8ffb800084bdfdf.zip)


Local:
![CleanShot 2021-12-28 at 03 33 41](https://user-images.githubusercontent.com/1409924/147562162-ae9dd5ad-e891-4a83-8cf8-c5d469e58447.png)


Live:
![CleanShot 2021-12-28 at 03 32 59](https://user-images.githubusercontent.com/1409924/147562102-435513c9-c666-449a-b341-41f2c73a2456.png)

**Comment by iankduffy** [comment]
Had the same issue removing CSS optimizations fixed it. Not sure the reason why it is failing though.

**Comment by ascorbic** [comment]
Hi @iankduffy: yes, you should never use asset optimizations with frameworks like Next which perform their own optimization. We've updated the docs to make this clearer.

**Comment by q-luisnesi** [comment]
Hi I have the same issue but asset optimisation is disabled and not toml file for redirect is created can someone help us to identify the real reason why this is happening. Our project is still in early stages.

**Comment by alex-major-digital** [comment]
> Hi I have the same issue but asset optimisation is disabled and not toml file for redirect is created can someone help us to identify the real reason why this is happening. Our project is still in early stages.

Same issue here, recently just happened after making a small CSS push

**Comment by shroudedcode** [comment]
@q-luisnesi @alex-major-digital Same here; in our case we didn't change anything about the code; we only had our CMS trigger a build due to some content changes and now our site is effectively down (without any CSS). I just reached out to Netlify support and will post an update if I hear anything!

**Comment by shroudedcode** [comment]
Hey guys, still don't know what caused this issue, but a temporary fix for us was going back to a previous deploy that we know still worked and pressing "Publish" to basically "bring back" that old version. Our site is back online now (but I'd imagine the next deploy would wreck it again).

**Comment by q-luisnesi** [comment]
@shroudedcode  I tried that solution but the problem is immediately the error came back once a new deploy landed.

**Comment by q-luisnesi** [comment]
@shroudedcode  agreed they are investigating that what support told me

**Comment by 4lm** [comment]
I have the same issue. Did a change in a Markdown file, pushed it to `main` which triggered a re-deploy, which resulted in 404s for all JS and CSS of that deploy. I took a deploy preview from Sunday to fix this. I think it's an issue on Netlifys end. Hopefully they will inform us soon what to do.
